openapi: 3.0.0
info:
  title: Argent Bank Transactions API
  description: API pour la gestion des comptes et transactions bancaires.
  version: 1.0.0
servers:
  - url: https://api.argentbank.com

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    adminAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Token d’authentification administrateur"

security:
  - bearerAuth: []  # Authentification par défaut pour les utilisateurs

paths:
  /accounts/{accountId}:
    parameters:
      - name: accountId
        in: path
        required: true
        schema:
          type: string
        description: ID unique du compte client

    get:
      summary: Récupérer les informations d'un compte client
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Détails du compte client
          content:
            application/json:
              schema:
                type: object
                properties:
                  accountId:
                    type: string
                    example: "acc_1r3k7"
                  accountName:
                    type: string
                    example: "Compte principal"
                  balance:
                    type: number
                    example: 5000.75
                  availableBalance:
                    type: number
                    example: 4800.50
        "401":
          description: Non autorisé
        "404":
          description: Compte non trouvé

  /transactions:
    get:
      summary: Récupérer les transactions du mois en cours pour un compte spécifique
      security:
        - bearerAuth: []
      parameters:
        - name: accountId
          in: query
          required: true
          schema:
            type: string
          description: ID unique du compte client
      responses:
        "200":
          description: Liste des transactions du mois en cours
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactions:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "txn_001"
                        date:
                          type: string
                          format: date-time
                          example: "2025-02-01T14:30:00Z"
                        description:
                          type: string
                          example: "Achat en ligne"
                        amount:
                          type: number
                          example: -50.00
                        balance:
                          type: number
                          example: 4950.75
        "401":
          description: Non autorisé

  /transactions/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: ID unique de la transaction
        
    get:
      summary: Récupérer les détails d'une transaction
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Détails de la transaction
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "txn_001"
                  transactionType:
                    type: string
                    example: "Electronic"
                  categoryId:
                    type: number
                    example: 3
                  categoryName:
                    type: string
                    example: "Food"
                  note:
                    type: string
                    example: "Déjeuner avec des collègues"
        "401":
          description: Non autorisé
        "404":
          description: Transaction non trouvée

    patch:
      summary: Modifier partiellement une transaction (seuls `categoryId`, `categoryName` et `note` peuvent être modifiés)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                categoryId:
                  type: number
                  example: 7
                categoryName:
                  type: string
                  example: "Transport"
                note:
                  type: string
                  example: "Trajet en taxi"
      responses:
        "200":
          description: Transaction mise à jour avec succès
        "400":
          description: Erreur de validation
        "401":
          description: Non autorisé
        "404":
          description: Transaction non trouvée
